"""initial

Revision ID: 35312d69b758
Revises: 
Create Date: 2025-02-09 13:10:29.039414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35312d69b758'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('workload', postgresql.ENUM('Fulltime', 'Parttime', name='workload'), nullable=False),
    sa.Column('work_location', postgresql.ENUM('Office', 'Remote', 'Hybrid', name='worklocation'), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('award', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('departments')
    # ### end Alembic commands ###
