"""Initial

Revision ID: 636d9c98e44a
Revises: 
Create Date: 2025-05-02 15:14:03.439536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '636d9c98e44a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('employees',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('workload', postgresql.ENUM('Fulltime', 'Parttime', name='workload'), nullable=False),
    sa.Column('work_location', postgresql.ENUM('Office', 'Remote', 'Hybrid', name='worklocation'), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('award', sa.Integer(), nullable=False),
    sa.Column('current_kpi', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.Column('sm_link', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.oid'], ),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('sm_link')
    )
    op.create_table('kpi_records',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('employee_oid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_oid'], ['employees.oid'], ),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('date_added', 'employee_oid', name='unique_date_employee_kpi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_records')
    op.drop_table('employees')
    op.drop_table('events')
    op.drop_table('departments')
    # ### end Alembic commands ###
