services:
  app:
    image: hrms:latest
    build:
      context:
        ../.
    container_name: main_app
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_HOST: ${POSTGRES_HOST}
       POSTGRES_PORT: ${POSTGRES_PORT}
       DEBUG: ${DEBUG}
       PYTHONPATH: ${PYTHONPATH}
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      database:
        condition: service_healthy


  database:
    image: postgres:latest
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    volumes:
      - hrms_db:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  hrms_db:
